"""Initial migration

Revision ID: ae8eb72e15d8
Revises: 
Create Date: 2025-02-18 18:58:21.994745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8eb72e15d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('books', 'published_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('books', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.alter_column('books', 'published_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
